# hugo server --minify --themesDir ../.. --baseURL=http://0.0.0.0:1313/theme/hugo-book/

baseURL = 'https://teddylu0219.github.io'
languageCode = 'en-us'
title = "Teddy's Notes"
theme = 'hugo-book'

[params]
    BookSearch = false
